# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saakar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='kill_loser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fight',
            name='result',
            field=models.CharField(choices=[('H1', 'Hero 1 won'), ('H2', 'Hero 2 won')], default='H1', max_length=2),
        ),
        migrations.AlterField(
            model_name='hero',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
